[tool.poetry]
name = "drvi"
version = "1.0.0"
description = "Disentangled Generative Representation of Single Cell Omics"
authors = ["Amir Ali moinfar <moinfar.amirali@gmail.com>"]
readme = "README.md"
packages = [{include = "drvi"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
torch = "2.1.0"
lightning = "<2.1,>=2.0"
scanpy = "1.9.5"
scikit-learn = ">=1.5.1"
scipy = ">=1.11.3"
scvi-tools = "1.0.4"
# TODO: Remove when scvi-tools and jax become ok again
jax = "<=0.4.20"
jaxlib = "<=0.4.20"
# END_TODO
anndata = ">=0.10.2"
numpy = ">=1.26.1"
pandas = ">=1.2.0"
merlin-dataloader = "23.8.0"
# lightning-cloud depends on boto3 that is currently not compatible with urllib3 so poetry resolution takes forever
# TODO: update this when this resolved: https://github.com/boto/botocore/issues/2926
urllib3 = "<2"

[tool.poetry.dev-dependencies]
# Formatting
black = "23.10.1"
leidenalg = "^0.10.1"
pytest = "^7.4.3"
# Docs
sphinx = "^4.0"
sphinx-autodoc-typehints = "^1.12.0"
sphinx-rtd-theme = "^0.5.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
